//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int MediaId { get; set; }
        public string ReviewDate { get; set; }
        public string Reviewer { get; set; }
        public string ReviewerLocation { get; set; }
        public string ReviewTitle { get; set; }
        public int Rating { get; set; }
        public string ReviewContent { get; set; }
    
        public virtual User User { get; set; }
        public virtual Media Medium { get; set; }
    }
}
